---
title: "HW1_207"
author: "RafaelCatoiaPulgrossi"
date: "2023-04-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr) ; library(ggplot2)
```

# Ex 1

```{r}
posterior_prop <- function(theta){
  
  return(
    (theta^3)*(1-theta)^13+
      (theta^4)*(1-theta)^12+
      (theta^5)*(1-theta)^11
  )
}

parametric_space <- seq(0.001,1,0.001)

plot(parametric_space,posterior_prop(theta=parametric_space),
     type='l',ylab='proportional to the density')
```


# Ex 5

## a 
```{r}
y <- c(43,44,45,46.5,47.5)
M=1000

parametric_space <- seq(0,100,1/M)

q_theta_given_y = function(x,theta){
  result <- 1
  for ( i in 1:length(x)){
    result = result * (1/(1+(x[i]-theta)^2))
  }
  return(result/100)
}


## unormalized density
unormalized_density <- q_theta_given_y(y,parametric_space)

## summing the heights of the bins
normalizing_constant <-  sum(unormalized_density/M)

#plotting the normalized density
plot(parametric_space,
     unormalized_density/normalizing_constant,
     type='l',
     ylab = 'normalized density')

normalized_density <-  unormalized_density/normalizing_constant
```

## b
```{r}
sample_theta <- sample(parametric_space,prob = normalized_density,size = 1000)
hist(sample_theta)
```

## c
```{r}
set.seed(57)
predictive_distribution <- rcauchy(1000,scale = 1,location = sample_theta)
plot(density(predictive_distribution))

plot(density(predictive_distribution),xlim=c(30,60))
abline(v=mean(y),col='forestgreen')
mean(predictive_distribution) ; sd(predictive_distribution)
```




# Ex 6

```{r Gibbs}

x_given_y <- function(constant,y){
  a <- max(0,y-constant)
  b <- min(y+constant,1)
  return(runif(1,a,b))
}

y_given_x <- function(constant,x){
  a <- max(0,x-constant)
  b <- min(x+constant,1)
  return(runif(1,a,b))
}


gibbs_ex6 <- function(B=1000,constant){
  set.seed(1000)
  samples <- data.frame(x=NA,y=NA)
  new_x <- 0.5 #initial value for x
  for(i in 1:(B)){
    #calculating p(y|x=new_x)
    new_y <- y_given_x(x = new_x,constant = constant) 
    #calculating p(x|y=new_y)
    new_x <- x_given_y(y = new_y,constant = constant)
    samples <-rbind(samples, c(new_x,new_y))
  }
  return(samples[-1,])
}

sample_0.3 <- gibbs_ex6(B = 1000,0.3)
sample_0.05 <- gibbs_ex6(B = 1000,0.05)
sample_0.01 <- gibbs_ex6(B = 1000,0.01)


par(mfrow=c(3,4))
constant<-0.3
plot(sample_0.3$x,type='l',col=scales::alpha('deepskyblue',0.5))
lines(sample_0.3$y,type='l',col=scales::alpha('firebrick',0.5))
plot(sample_0.3)
abline(constant,1,col='blue')
abline(-constant,1,col='blue')
abline(0,1,col='blue')
acf(sample_0.3$x)
acf(sample_0.3$y)

constant<-0.05
plot(sample_0.05$x,type='l',col=scales::alpha('deepskyblue',0.5))
lines(sample_0.05$y,type='l',col=scales::alpha('firebrick',0.5))
plot(sample_0.05)
abline(constant,1,col='blue')
abline(-constant,1,col='blue')
abline(0,1,col='blue')
acf(sample_0.05$x)
acf(sample_0.05$y)

constant<-0.01
plot(sample_0.01$x,type='l',col=scales::alpha('deepskyblue',0.5))
lines(sample_0.01$y,type='l',col=scales::alpha('firebrick',0.5))
plot(sample_0.01)
abline(constant,1,col='blue')
abline(-constant,1,col='blue')
abline(0,1,col='blue')
acf(sample_0.01$x)
acf(sample_0.01$y)

```




# Ex 8 - 3.4

```{r}
nsim <- 10000
posterior_simulation <- data.frame(
  p0 = rbeta(nsim,40,636),
  p1 = rbeta(nsim,23,569)
)


posterior_simulation = 
  posterior_simulation %>% 
  mutate(odds_p0=p0/(1-p0),
         odds_p1=p1/(1-p1),
         odds_ratio = odds_p1/odds_p0)

posterior_simulation %>% 
  summarise(
    Min = min(odds_ratio),
    Mean = mean(odds_ratio),
    Median = median(odds_ratio),
    SD = sd(odds_ratio),
    Max = max(odds_ratio)) %>% 
  knitr::kable() %>% kableExtra::kable_styling()
```

```{r}
posterior_simulation %>% 
  ggplot(aes(x=odds_ratio))+
  geom_histogram() + 
  theme_bw()
```


```{r}
y_bar_control = 39/674
y_bar_treatment = 22/680

#Posterior probability 
sum(posterior_simulation$p0 > y_bar_control)/nsim

sum(posterior_simulation$p1 > y_bar_treatment)/nsim

sum(posterior_simulation$odds_ratio < 1)/nsim
```


## Now changing the sample size


```{r}
nsim <- 10000
posterior_simulation <- data.frame(
  p0 = rbeta(nsim,3,35),
  p1 = rbeta(nsim,2,35)
)


posterior_simulation = 
  posterior_simulation %>% 
  mutate(odds_p0=p0/(1-p0),
         odds_p1=p1/(1-p1),
         odds_ratio = odds_p1/odds_p0)

posterior_simulation %>% 
  summarise(
    Min = min(odds_ratio),
    Mean = mean(odds_ratio),
    Median = median(odds_ratio),
    SD = sd(odds_ratio),
    Max = max(odds_ratio)) %>% 
  knitr::kable() %>% kableExtra::kable_styling()
```

```{r}
posterior_simulation %>% 
  ggplot(aes(x=odds_ratio))+
  geom_histogram() + 
  theme_bw()
```


```{r}
y_bar_control = 2/34
y_bar_treatment = 1/34

#Posterior probability 
sum(posterior_simulation$p0 > y_bar_control)/nsim

sum(posterior_simulation$p1 > y_bar_treatment)/nsim

sum(posterior_simulation$odds_ratio < 1)/nsim
```



# Ex 10 

```{r}
# proportional to the posterior distribution that we
# are going to draw samples from
propto_posterior <- function(y=1.5,theta){
  numerator <- exp(-(1/2)*(y-theta)^2)
  denominator <- (1+theta^2)
  return(numerator/denominator)
}


n_it <- 10000 #number of samples to be generated
init_value <- 0.5 # initial value of theta 
proposal_dist <- function(theta){rnorm(1,theta,sd=2)} # we are going to use the normal distribution as proposal
post_sample <- rep(NA,n_it) #creating the vector that will store the samples
post_sample[1]=init_value #the first draw of the posterior is the initial value
accepted=0 # counting the accepted values to see the acceptance rate
# initializing the iteration
for (i in 2:n_it){
  candidate <- proposal_dist(post_sample[i-1]) 
  
  #calculating acceptance probability of the current point
  r = min(1,propto_posterior(theta = candidate) /
            propto_posterior(theta = post_sample[i-1]))
  
  #accepting the candidates with probability r
  if(runif(1)>r){
    # if not accepted, we will start the new iteration with the same point
    post_sample[i] <- post_sample[i-1]
  } else {
    # if accepted, we will move our chain to the candidate point and start the 
    # next iteration from this point
    post_sample[i] <- candidate
    accepted<-accepted+1
  }
}

accepted/n_it

randWalk_MH_diagnostics <- function(posterior_sample){
  a <- round(density(posterior_sample)$x[1],3) ; b <- round(density(posterior_sample)$x[length(density(posterior_sample)$x)],3)
  grid<- seq(a,b,0.001)
  par(mfrow=c(1,3))
  plot(grid,propto_posterior(theta = grid,y=1.5),type='l',lty=2,lwd=1.5)
  lines(density(posterior_sample),type='l',col='deepskyblue',lwd=1.5)
  legend(a,0.5,legend = c('prop_posterior','sample_density'),
         col=c('black','deepskyblue'),lwd = c(1.5,1.5), lty=c(2,1))
  plot(posterior_sample,type = 'l')
  acf(posterior_sample)
  par(mfrow=c(1,3))
}

randWalk_MH_diagnostics(post_sample)

summary(post_sample)
```


```{r}

n_it <- 10000 #number of samples to be generated
init_value <- 0.5 # initial value of theta
step <- 10
burn_in = 10000
proposal_dist <- function(theta){rnorm(1,theta,sd=2)} # we are going to use the normal distribution as proposal
post_sample <- rep(NA,n_it) #creating the vector that will store the samples
post_sample[1]=init_value #the first draw of the posterior is the initial value
accepted=0 # counting the accepted values to see the acceptance rate

# initializing the iteration
for (i in 2:(n_it*5+burn_in)){
  candidate <- proposal_dist(post_sample[i-1]) 
  
  #calculating acceptance probability of the current point
  r = min(1,propto_posterior(theta = candidate) /
            propto_posterior(theta = post_sample[i-1]))
  
  #accepting the candidates with probability r
  if(runif(1)>r){
    # if not accepted, we will start the new iteration with the same point
    post_sample[i] <- post_sample[i-1]
  } else {
    # if accepted, we will move our chain to the candidate point and start the 
    # next iteration from this point
    post_sample[i] <- candidate
    accepted<-accepted+1
  }
}

accepted/(n_it*step+burn_in)


post_sample <- post_sample[-c(1:burn_in)]
post_sample <- post_sample[seq(1,length(post_sample),step)]


randWalk_MH_diagnostics(post_sample)

post_sample %>% summary()
post_sample %>% sd()
post_sample %>% length()
```

